spring:
  application:
    name: ROLES-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/LocalDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Use `update` for development; change to `validate` or `none` in production.
    show-sql: true # Displays SQL queries in the console.
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect  
server:
  port: 9092
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
